// Guard: the auto-ship code-lane dispatch prompt must tell each builder that a
// fresh worktree needs BOTH `pnpm install` and `pnpm build` before its first test
// run, and must name the failure signature that skipping the build produces.
//
// Why this exists (TASK-378). A worktree carries tracked files only. `node_modules`
// and every package's tsc-built `dist/` are gitignored, so both are absent in a
// builder's fresh worktree. The two omissions fail very differently:
//
//   - No install    -> every package fails instantly at spawn time (`spawn ENOENT`
//                      in the probe below; older sessions logged the same thing as
//                      `vitest: not found`). Loud, self-diagnosing, harmless.
//   - No build      -> workspace packages resolve through their `exports` to
//                      `./dist/...`, so every test file that imports a sibling
//                      `@ax/*` dies at LOAD with `Failed to resolve entry for
//                      package "@ax/..."` -- or, for a declared SUBPATH export such
//                      as `@ax/skills/manifest`, with the sibling spelling `Failed to
//                      resolve import "@ax/.../..."`. Two messages, one cause, one
//                      fix. That reads like the branch broke the repo, and an agent
//                      can spend a long time debugging its own innocent diff.
//
//                      The subpath spelling is much rarer: in the probe below it is
//                      2 occurrences of `@ax/skills/manifest` and 1 of
//                      `@ax/validator-routine/frontmatter`, against 363 files with
//                      the `resolve entry` spelling. So the guard pins only
//                      `resolve entry` -- accepting both would let a bullet that
//                      names ONLY the rare variant satisfy it.
//
// MEASURED (2026-09-17, probe worktree of `main` at 6bd2b280, installed but not
// built, `pnpm -r --no-bail run test`): **363 test files across 68 packages**
// failed to load with that error; 403 test files failed in total. The same suite
// over a BUILT tree produces **zero** occurrences of that error, which is the
// counterfactual worth having -- all 363 were an environment artifact and not one
// of them was a defect in anyone's branch. The card that
// ordered this guard said "~41", sourced from
// `docs/plans/2026-09-16-auto-ship-run-handoff.md`; that is roughly 9x low, and no
// single package fails 41 either, so it was not a per-package figure. The remedy
// was timed in a SECOND fresh worktree of the same commit the same day (not the
// probe above): `pnpm install --frozen-lockfile` 7.6s, `pnpm build` 17.1s. About
// 25 seconds against a debugging session.
//
// The knowledge was ALREADY in `.claude/memory/` -- thirteen rows across meta.md,
// mistakes.md and patterns.md tell you to install and build a fresh worktree
// (`grep -n worktree .claude/memory/{meta,mistakes,patterns}.md | grep -E 'pnpm
// install|node_modules'`, counted before this card added a fourteenth) -- and it
// recurred anyway. That is the actual finding: memory is not where a builder reads
// at the moment it matters. The dispatch prompt is. And until this guard existed,
// the remedy lived on as an ORCHESTRATOR HABIT -- the orchestrator of the
// 2026-09-17 run reports hand-writing an install+build line into every one of its
// nine dispatches. Take that as the operator's account rather than something this
// test measured; the part not in dispute is that a habit lives in whoever is
// driving, is invisible to the next reader of the template, and disappears the
// first time a dispatch is generated by someone who does not remember it.
//
// WHAT THIS ASSERTS, AND WHY EACH PART EARNS ITS PLACE. The test extracts the
// `## Code-lane dispatch prompt` section of
// `.claude/skills/auto-ship/references/templates.md`, narrows to the BLOCKQUOTE
// inside it (the text actually handed to the builder, as opposed to the
// orchestrator-facing prose above it), and requires ONE bullet to carry all three
// of the following. Each is pinned because a plausible edit breaks exactly that
// one and nothing else; each was run as a mutant against this file rather than
// reasoned about.
//
//   1. An INSTALL command. Deleting the bullet outright fails here. This is the
//      baseline mutation check: the guard was RED against the pre-fix template,
//      whose builder prompt said nothing about install or build at all.
//
//   2. A full-workspace BUILD command, in the SAME bullet. This is the assertion
//      that matters most, because install-without-build is precisely the 363-file
//      failure mode -- an edit that trims the bullet down to "run `pnpm install
//      --frozen-lockfile`" would satisfy property 1 while shipping the whole bug
//      back. Same-bullet, because "install" in one bullet and "build" in an
//      unrelated one is not this instruction.
//
//   3. The `Failed to resolve entry` SIGNATURE, in the same bullet. The remedy and
//      the symptom have to arrive together: a builder who skipped the build reads
//      a wall of red and needs to recognize it on sight. Separating the diagnosis
//      from the instruction is a partial regression of the thing this card is
//      about -- putting the knowledge where the agent reads it at the moment it
//      matters.
//
//   4. Placement: inside the blockquote, not the prose above it. Guidance
//      addressed to the orchestrator ("remember to tell builders to build...")
//      reproduces the exact defect being fixed, since it still depends on a human
//      remembering. A well-meaning edit that relocates the bullet upward must
//      fail, and gets its own diagnosis so the failure says why.
//
// Lives in scripts/__tests__/, which `pnpm test:scripts` runs unconditionally --
// no network, no build, no subprocess (same pattern as the sibling guard
// autoship-dispatch-scratch-scoping.test.js).
//
// ON THE DUPLICATED PARSE HELPERS. `sectionBody`/`blockquote`/`bullets` below are
// near-copies of that sibling's. Every guard in this directory is self-contained --
// there is no shared helper module and no precedent for one --
// and these are three short pure functions over markdown. Two copies is cheaper
// than the indirection. If a THIRD guard ever parses this same file (TASK-392 is
// a candidate), extract them then.

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, it, expect } from 'vitest';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const TEMPLATES_PATH = join(REPO_ROOT, '.claude', 'skills', 'auto-ship', 'references', 'templates.md');

const templatesText = readFileSync(TEMPLATES_PATH, 'utf8');

/**
 * The body of a `## `-level section, up to the next `## ` heading or EOF.
 *
 * Matched line by line with `startsWith('## ')`, so a `## ` appearing inside a
 * blockquote (`> ## `) or an indented block cannot end the section early.
 */
function sectionBody(text, heading) {
  const lines = text.split('\n');
  const start = lines.findIndex((l) => l === `## ${heading}`);
  if (start === -1) return undefined;
  const rest = lines.slice(start + 1);
  const end = rest.findIndex((l) => l.startsWith('## '));
  return (end === -1 ? rest : rest.slice(0, end)).join('\n');
}

/**
 * The blockquote inside a section, with the `> ` markers stripped -- i.e. the
 * literal prompt text a builder receives.
 *
 * Returns the quoted lines only. Everything NOT quoted is orchestrator-facing
 * prose, which is what property 4 above needs to tell apart.
 */
function blockquote(body) {
  return body
    .split('\n')
    .filter((l) => l === '>' || l.startsWith('> '))
    .map((l) => l.slice(2))
    .join('\n');
}

/**
 * Split markdown prose into top-level `- ` bullets, each carrying its own
 * indented continuation lines.
 *
 * KNOWN LIMIT, accepted: only `- ` bullets are recognized, so reformatting the
 * prompt to `* ` bullets would redden this guard even though the property still
 * holds. The file uses `- ` throughout and is headed "copy these literally, do not
 * paraphrase". A reformat would fail legibly (see the bullet-count vacuity check
 * below, which reports exactly that) rather than pass silently, which is the right
 * direction to be wrong in.
 */
function bullets(text) {
  const out = [];
  for (const line of text.split('\n')) {
    if (/^- /.test(line)) out.push(line);
    else if (out.length > 0) out[out.length - 1] += `\n${line}`;
  }
  return out;
}

// `pnpm install` (or its `pnpm i` alias). Flags after it are irrelevant here --
// `--frozen-lockfile` is the right one, but a bullet that says plain
// `pnpm install` has still told the builder the thing that matters.
const INSTALL_CMD = /\bpnpm\s+(?:install|i)\b/;

// A WHOLE-WORKSPACE build command: `pnpm build`, `pnpm run build`, `pnpm -r build`,
// or the `tsc --build` it delegates to. Deliberately does NOT match a filtered
// build (`pnpm --filter @ax/x build`), which leaves every other package's `dist/`
// empty and so does not prevent the failure this guard exists for. Deliberately
// does NOT match the bare English word "build" either: prose can say "build" all
// day while the command has been edited out, and that mutant is exactly property 2.
const BUILD_CMD = /\bpnpm(?:\s+-\S+)*\s+(?:run\s+)?build\b|\btsc\s+--build\b/;

// The error a builder actually sees when it skips the build. Naming it is what
// turns 363 red files from "my branch is broken" into "I forgot to build".
const RESOLVE_SIGNATURE = /Failed to resolve entry/;

const codeLaneBody = sectionBody(templatesText, 'Code-lane dispatch prompt');
const codeLanePrompt = codeLaneBody === undefined ? undefined : blockquote(codeLaneBody);
const promptBullets = codeLanePrompt === undefined ? [] : bullets(codeLanePrompt);

describe('auto-ship code-lane dispatch tells builders to install+build a fresh worktree (TASK-378)', () => {
  it('finds the code-lane dispatch prompt and its bullets — a broken parse would pass everything below', () => {
    // Vacuity guard. Every assertion below is a search over text this parse
    // produced, so an empty parse makes all of them trivially green. Fail HERE,
    // legibly, rather than reporting success for a file nobody read.
    expect(
      codeLaneBody,
      `no "## Code-lane dispatch prompt" section in ${TEMPLATES_PATH}`,
    ).not.toBeUndefined();
    expect(
      codeLanePrompt.length,
      'the code-lane section has no `> `-quoted prompt body — the blockquote scan broke',
    ).toBeGreaterThan(500);
    expect(
      promptBullets.length,
      'the code-lane prompt has no `- ` bullets — it was reformatted and this guard needs updating',
    ).toBeGreaterThanOrEqual(5);
  });

  it('tells the builder, in the prompt itself, to install AND build before testing', () => {
    if (codeLanePrompt === undefined) return; // reported by the test above

    const complete = promptBullets.filter(
      (b) => INSTALL_CMD.test(b) && BUILD_CMD.test(b) && RESOLVE_SIGNATURE.test(b),
    );

    const diagnosis = (() => {
      const installing = promptBullets.filter((b) => INSTALL_CMD.test(b));
      if (installing.length > 0 && !installing.some((b) => BUILD_CMD.test(b))) {
        return 'a bullet says to install but names no whole-workspace build command — installing without building IS the failure mode (363 test files across 68 packages, measured 2026-09-17)';
      }
      if (installing.some((b) => BUILD_CMD.test(b))) {
        return 'the install+build bullet does not name the `Failed to resolve entry` signature, so a builder who skips the build reads the resulting wall of red as real breakage';
      }
      if (INSTALL_CMD.test(codeLaneBody) || BUILD_CMD.test(codeLaneBody)) {
        return 'the install/build instruction sits in the orchestrator-facing prose, not in the `> `-quoted builder prompt — that is an orchestrator habit, not a fix';
      }
      return 'the builder prompt never says a fresh worktree needs `pnpm install --frozen-lockfile && pnpm build`, so its first test run fails on unbuilt workspace deps and looks like real breakage';
    })();

    expect(complete.length, `${TEMPLATES_PATH}: ${diagnosis}`).toBeGreaterThanOrEqual(1);
  });
});
