// Guard: the auto-ship code-lane dispatch prompt must tell each builder to keep
// its temp files in a TASK-SCOPED scratch directory.
//
// Why this exists (TASK-377). The agent scratchpad directory is per-SESSION, and
// a wave of `yolo-ship` builders dispatched by one auto-ship run are subagents of
// that one session -- so all of them are handed the SAME scratchpad path. Three
// builders in one wave each wrote `<scratchpad>/pr-body.md`; the last writer won
// and a sibling's PR body was silently replaced. That builder happened to notice.
// One that does not notice opens a PR whose body describes a different card's
// work, and nothing in CI can see it.
//
// The fix is one bullet in the dispatch prompt. The reason it needs a guard is
// that it had already been working for a while as an ORCHESTRATOR HABIT --
// reported by the orchestrator of the 2026-09-16 run, which hand-wrote a
// per-task scratch line into every dispatch and saw eight concurrent builders
// finish without a collision. Take that as the operator's account rather than
// something this test measured; what matters here is the part that is not in
// dispute. A habit is not a fix. It lives in whoever is driving, it is
// invisible to the next reader of the template, and it disappears the first
// time a dispatch is generated by something other than the person who
// remembers it.
//
// WHAT THIS ASSERTS, AND WHY EACH PART EARNS ITS PLACE. The test extracts the
// `## Code-lane dispatch prompt` section of
// `.claude/skills/auto-ship/references/templates.md`, then narrows to the
// BLOCKQUOTE inside it -- the text that is actually handed to the builder, as
// opposed to the orchestrator-facing prose above it. Three properties, each
// pinned because a plausible edit breaks exactly that one and nothing else:
//
//   1. A scratch/temp-directory instruction EXISTS in the builder-facing prompt.
//      Fails against the pre-fix template, whose builder prompt said nothing at
//      all about where temp files go. (The word `scratch` did not appear
//      anywhere in that file; the single `tmp` in it was in the
//      failure-signature normalization section, which strips tmp paths out of a
//      signature -- a different concept in a different section, and not
//      something this scan can reach.) This is the mutation check that matters
//      most: the guard was RED before the bullet was written.
//
//   2. It is inside the blockquote, not in the prose above it. This is the
//      habit-vs-fix distinction stated as an assertion. Guidance addressed to
//      the orchestrator ("remember to tell builders...") reproduces the exact
//      defect this card fixes -- it still depends on a human remembering -- so a
//      well-meaning edit that relocates the bullet upward must fail.
//
//   3. The instruction names the task id as a PATH SEGMENT (`/<TASK-ID>/`), not
//      merely somewhere in the sentence. Without this, a template that said
//      "write temp files to `<scratchpad>/`" -- i.e. the shared directory that
//      caused the collision, now with an instruction pointing AT it -- would
//      satisfy property 1 and ship the bug back. `<TASK-ID>` is already one of
//      the placeholders the orchestrator substitutes for this template, so the
//      rendered dispatch is a concrete path with no new placeholder to forget.
//
// Lives in scripts/__tests__/, which `pnpm test:scripts` runs unconditionally --
// no network, no build, no subprocess (same pattern as no-raw-nul-bytes.test.js).

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, it, expect } from 'vitest';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const TEMPLATES_PATH = join(REPO_ROOT, '.claude', 'skills', 'auto-ship', 'references', 'templates.md');

const templatesText = readFileSync(TEMPLATES_PATH, 'utf8');

/**
 * The body of a `## `-level section, up to the next `## ` heading or EOF.
 *
 * Anchored at column 0 with the `m` flag so a `## ` appearing inside a fenced
 * block or a blockquote (`> ## `) cannot end the section early.
 */
function sectionBody(text, heading) {
  const lines = text.split('\n');
  const start = lines.findIndex((l) => l === `## ${heading}`);
  if (start === -1) return undefined;
  const rest = lines.slice(start + 1);
  const end = rest.findIndex((l) => l.startsWith('## '));
  return (end === -1 ? rest : rest.slice(0, end)).join('\n');
}

/**
 * The blockquote inside a section, with the `> ` markers stripped -- i.e. the
 * literal prompt text a builder receives.
 *
 * Returns the quoted lines only. Everything NOT quoted is orchestrator-facing
 * prose, which is what property 2 above needs to tell apart.
 */
function blockquote(body) {
  return body
    .split('\n')
    .filter((l) => l === '>' || l.startsWith('> '))
    .map((l) => l.slice(2))
    .join('\n');
}

/**
 * Split markdown prose into top-level `- ` bullets, each carrying its own
 * indented continuation lines.
 *
 * Properties 1 and 3 must hold of the SAME bullet. Testing them against the
 * whole prompt separately would pass a template that mentions a scratch dir in
 * one bullet and `<TASK-ID>` in an unrelated one -- which is not this fix.
 */
function bullets(text) {
  const out = [];
  for (const line of text.split('\n')) {
    if (/^- /.test(line)) out.push(line);
    else if (out.length > 0) out[out.length - 1] += `\n${line}`;
  }
  return out;
}

// A scratch/temp working directory, however the template chooses to name it.
// Deliberately broader than the one spelling in use, so a rename from
// "scratchpad" to "scratch dir" or "temp dir" is not reported as a regression.
const SCRATCH_MENTION = /scratch|\btmp\b|\btemp(?:orary)?\b/i;

// `<TASK-ID>` used as a DIRECTORY SEGMENT -- slashes on both sides. Prose that
// merely names the task id ("for <TASK-ID>, use the scratchpad") does not match,
// and must not: that is the shared-directory bug wearing an instruction's
// costume.
const TASK_SCOPED_PATH_SEGMENT = /\/<TASK-ID>\//;

const codeLaneBody = sectionBody(templatesText, 'Code-lane dispatch prompt');
const codeLanePrompt = codeLaneBody === undefined ? undefined : blockquote(codeLaneBody);

describe('auto-ship code-lane dispatch scopes the scratch dir per task (TASK-377)', () => {
  it('finds the code-lane dispatch prompt at all — a broken parse would pass everything below', () => {
    // Vacuity guard, in the house style. Every assertion below is a search over
    // text this parse produced, so an empty parse makes all of them trivially
    // green. The heading and the blockquote are both load-bearing: if either
    // scan silently stops matching, fail HERE with a legible message rather than
    // reporting success for a file nobody read.
    expect(
      codeLaneBody,
      `no "## Code-lane dispatch prompt" section in ${TEMPLATES_PATH}`,
    ).not.toBeUndefined();
    expect(
      codeLanePrompt.length,
      'the code-lane section has no `> `-quoted prompt body — the blockquote scan broke',
    ).toBeGreaterThan(500);
    // The prompt is the thing that gets `<TASK-ID>` substituted into it; if that
    // placeholder has vanished entirely, property 3 is testing a spelling that
    // no longer exists rather than the property it was written for.
    expect(
      codeLanePrompt.includes('<TASK-ID>'),
      'the code-lane prompt no longer uses the `<TASK-ID>` placeholder — this guard needs updating',
    ).toBe(true);
  });

  it('tells the builder, in the prompt itself, to use a task-scoped scratch directory', () => {
    if (codeLanePrompt === undefined) return; // reported by the test above

    const promptBullets = bullets(codeLanePrompt);
    const scoped = promptBullets.filter(
      (b) => SCRATCH_MENTION.test(b) && TASK_SCOPED_PATH_SEGMENT.test(b),
    );

    const diagnosis = (() => {
      if (promptBullets.some((b) => SCRATCH_MENTION.test(b))) {
        return 'a scratch/temp directory IS mentioned, but not as `…/<TASK-ID>/…` — a shared path is the collision';
      }
      if (SCRATCH_MENTION.test(codeLaneBody)) {
        return 'the scratch instruction sits in the orchestrator-facing prose, not in the `> `-quoted builder prompt — that is an orchestrator habit, not a fix';
      }
      return 'the builder prompt says nothing about where to put temp files, so every concurrent builder writes the same shared scratchpad path';
    })();

    expect(scoped.length, `${TEMPLATES_PATH}: ${diagnosis}`).toBeGreaterThanOrEqual(1);
  });
});
