export type {
  CapabilitySlot,
  SkillCapabilities,
  SkillSummary,
  SkillDetail,
  ResolvedSkill,
  SkillsListInput,
  SkillsListOutput,
  SkillsGetInput,
  SkillsGetOutput,
  SkillsUpsertInput,
  SkillsUpsertOutput,
  SkillsDeleteInput,
  SkillsDeleteOutput,
  SkillsResolveInput,
  SkillsResolveOutput,
  SkillsListDefaultsInput,
  SkillsListDefaultsOutput,
  SkillTier,
  BundleFile,
  CatalogRequest,
  CatalogSubmitInput,
  CatalogSubmitOutput,
  CatalogListRequestsInput,
  CatalogListRequestsOutput,
  CatalogAdmitInput,
  CatalogAdmitOutput,
  CatalogCandidate,
  ApprovedCapEntry,
  SkillsApprovedCapsListInput,
  SkillsApprovedCapsListOutput,
  SkillsApprovedCapsSetInput,
  SkillsApprovedCapsSetOutput,
  SkillsApprovedCapsRevokeInput,
  SkillsApprovedCapsRevokeOutput,
} from './types.js';

export { parseSkillManifest } from './manifest.js';
export type { ManifestCode, ParsedManifest, ParseResult } from './manifest.js';

export { createSkillsPlugin, type SkillsPluginConfig } from './plugin.js';
